[package]
name = "hugs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parser = { path = "../parser" }
petgraph = { version = "0.6.3", default-features = false }
rand = "0.8.5"

